
version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:8000"   # I like working on 80 since you don't need to specify and looking neat on URL

    volumes:
      - .:/code
      - ./ExtractPdfWeb/config/nginx:/etc/nginx/conf.d
      - ./ExtractPdfWeb/static:/static
    depends_on:
      - web


  db:
    image: postgres

  redis:
    image: redis:latest
    hostname: redis
    ports:
     - '6379:6379'


  web:
    build: .
    command: bash -c "cd ExtractPdfWeb && python manage.py makemigrations && python manage.py migrate && gunicorn ExtractPdfWeb.wsgi -b 0.0.0.0:8000"     #production mode
    #command: bash -c "cd ExtractPdfWeb && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"  # develop mode
    volumes:
      - .:/code
      - ./ExtractPdfWeb/static:/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - worker
    links:
      - db
      - redis

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code/ExtractPdfWeb
    command: celery worker -A ExtractPdfWeb.celery --loglevel=info
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - redis




