
version: '2'

services:

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: swdzswdz
      MYSQL_USER: sergio
      MYSQL_PASSWORD: swdzswdz
      MYSQL_DATABASE: Extractor-PDF

  redis:
    image: redis:latest
    hostname: redis
    ports:
     - '6379:6379'

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - worker

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery worker -A ExtractPdfWeb.celery --loglevel=info
    volumes:
      - .:/code
    links:
      - redis
