# Generated by Django 2.0.6 on 2018-07-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='documento',
            field=models.FileField(upload_to='./'),
        ),
    ]
