# Generated by Django 2.0.6 on 2018-08-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180812_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioInferior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fehca_publicacion', models.DateField()),
                ('publicado', models.BooleanField(default=False)),
                ('script', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnuncioLateral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fehca_publicacion', models.DateField()),
                ('publicado', models.BooleanField(default=False)),
                ('script', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnuncioSuperior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fehca_publicacion', models.DateField()),
                ('publicado', models.BooleanField(default=False)),
                ('script', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='explicacion',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='explicacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
