# Generated by Django 2.0.6 on 2018-08-12 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180812_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncioinferior',
            name='fehca_publicacion',
        ),
        migrations.RemoveField(
            model_name='anunciolateral',
            name='fehca_publicacion',
        ),
        migrations.RemoveField(
            model_name='anunciosuperior',
            name='fehca_publicacion',
        ),
        migrations.RemoveField(
            model_name='explicacion',
            name='fehca_publicacion',
        ),
        migrations.AddField(
            model_name='anuncioinferior',
            name='fecha_publicacion',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anunciolateral',
            name='fecha_publicacion',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anunciosuperior',
            name='fecha_publicacion',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='explicacion',
            name='fecha_publicacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
