# Generated by Django 2.0.6 on 2018-08-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180812_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncioinferior',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anunciolateral',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anunciosuperior',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='explicacion',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
