# Generated by Django 2.0.6 on 2018-08-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180812_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='proceso',
            field=models.TextField(blank=True, choices=[('B', 'B'), ('T', 'T'), ('TB', 'TB')]),
        ),
    ]
